### PR TITLE
modified cake eating lecture

### PR DESCRIPTION
**Pull request by shizejin**
I did the following changes

1. I made some small modifications to Harvey's well-written lecture, including correcting typos and trying to make the math a little clearer,
2. I added a section discussing Euler function iteration. I may add more discussion for this part this week.
3. I added exercise 3 which asks readers to `jit` the code.

It would be great if @jstac and @Harveyt47 would be willing to give me some comments on the changes I made.

### CODE REVIEW

**Comment by jstac** [comment]
Hi @shizejin, I can't see which changes you made.  Perhaps the file wasn't versioned before you started making your changes?

Anyway, I'm going to merge this and then we can iterate.

**Comment by jstac** [comment]
Actually I'm going to close this and merge your work manually.

**Comment by shizejin** [comment]
@jstac sorry for the inconvenience. I was actually confused as the master branch seemed quite different from the one I forked — when I made the PR, there seemed to be no existing cake eating rst file in the repo. I am not sure where I got wrong.. but thank you very much for helping me merge the changes!

**Comment by jstac** [comment]
No problem @shizejin, I made some unnecessary changes to master, which was confusing.

**Pull request closed without merging**
