### PR TITLE
add endogenous grid method ifp.

### PR DESCRIPTION
**Pull request by shizejin**
Hi @jstac, here is the code for solving the simple ifp model using time iteration and endogenous grid method.

I have a minor question regarding the model: since we have changed the definition of a, should we also change the borrowing constraint to be "a-c>-b"? Currently the code does not deal with the borrowing constraint, and I would love to modify the code when things get clear.

@Harveyt47 I confirmed that the numerical solution gets weird when the capital return rate is high (e.g. r=0.06). I think this makes sense since if $\beta * R$ is above a certain threshold, there is no stable optimal consumption path as agents have incentive to consume in the infinitely distant future. @jstac could you please let me know if I understand this correctly?

### CODE REVIEW

**Comment by jstac** [comment]
Ah, that might be it.  For sufficiently high R the objective function is infinite and the policy is not well defined.  

At least for policy function iteration, we need to stick to cases where beta * R < 1.  For value function iteration the condition might be weaker, but perhaps let's just stick to those cases anyway.

Does that make your problem go away @Harveyt47 ?

**Comment by jstac** [comment]
Ah, that might be it.  For sufficiently high R the objective function is infinite and the policy is not well defined.  

At least for policy function iteration, we need to stick to cases where beta * R < 1.  For value function iteration the condition might be weaker, but perhaps let's just stick to those cases anyway.

Does that make your problem go away @Harveyt47 ?

**Comment by jstac** [comment]
Hi @shizejin , I've merged this but one comment so far.  You say that, since u' is one-to-one, you can pass its inverse through the max in the Euler equation.

In fact, since u' is decreasing so is u' inverse, so we need to replace max with min.

That is, for decreasing f and scalars a, b, we have 

f (max{a, b}) = min{ f(a), f(b)}.

Agree?

Also, a small note with your exposition is that the first order condition doesn't have to be satisfied because we can have a boundary solution for c.  That's why the max appears.

Perhaps you are aware of these things already.

**Comment by shizejin** [comment]
@jstac I totally agree.

1. yes after inversion it should be min. I will modify the math. In the code I am using minimum so it should be correct.
2. I must be sloppy when I discuss this part. I will try to polish the analysis for this and to be clearer.

**Pull request merged**
